In [2]:
import numpy as np


In [3]:
mylist = [1, 2, 3, 4, 5]

In [4]:
type(mylist)

list

In [6]:
mylist = np.array(mylist)

In [7]:
type(mylist)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
len(np.linspace(0,10,21))

21

An **identity matrix** is a special square matrix that acts like the number 1 in multiplication for matrices. Just like multiplying any number by 1 doesn't change the value of the number, multiplying any matrix by an identity matrix leaves the original matrix unchanged.

Here's a more detailed breakdown of identity matrices:

* **Square Matrix:** An identity matrix is always square, meaning it has the same number of rows and columns.
* **Ones on the Diagonal:**  The elements on the main diagonal, running from the top left corner to the bottom right corner, are all 1s.
* **Zeros Elsewhere:** All the other elements outside the diagonal are 0s.
* **Notation:**  An identity matrix of size n (where n is the number of rows and columns) is denoted by In or simply I.

Here are some examples of identity matrices:

* A 2x2 identity matrix:
  ```
  [1 0]
  [0 1]
  ```
* A 3x3 identity matrix:
  ```
  [1 0 0]
  [0 1 0]
  [0 0 1]
  ```

If you multiply any matrix A by the corresponding identity matrix In, the result will be A itself. This property makes identity matrices essential for various operations in linear algebra.

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])