In [1]:
import numpy as np

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]) #random



In [7]:
np.random.rand(1)

array([0.32336474])

In [8]:
np.random.rand(3)

array([0.83990532, 0.46996899, 0.61525044])

In [5]:
np.random.rand(4,5)

array([[0.23137022, 0.01082593, 0.4119278 , 0.34462132, 0.08374999],
       [0.86865065, 0.3678941 , 0.91237733, 0.45844464, 0.38016021],
       [0.82855306, 0.46986619, 0.79242653, 0.56623165, 0.55598959],
       [0.70577858, 0.17920313, 0.66717735, 0.3917378 , 0.55423473]])

## Standard normal distribution

The standard normal distribution is a special kind of distribution that statisticians and mathematicians often use to understand how data points in a certain situation are spread out. It's like if you measured how tall all the students in your school are, then plotted these heights on a graph to see which heights are most common, which are less common, and so on.

Here’s a simpler way to think about it: Imagine you have a large number of coins and you flip all of them. Most of the time, you'll get about half heads and half tails, right? But sometimes, you might get a few more heads or a few more tails. If you plot these results on a graph after doing many, many coin flips, you’d get a shape that looks like the standard normal distribution.

The standard normal distribution has a few special features:

1. **Shape**: It looks like a bell, so it's often called the "bell curve." The middle of the bell is the average result (like getting half heads and half tails), and it's the most likely outcome.
2. **Mean (average)**: In a standard normal distribution, the mean is always 0. This is like adjusting our scale so that the average result (the center of the bell) is at zero on the graph.
3. **Standard Deviation**: This tells us how spread out the data is around the mean. In a standard normal distribution, the standard deviation is always 1. This means that most of the data (about 68% of it) falls within one standard deviation from the mean (between -1 and 1 on our graph).

**Example**: Suppose we measure the intelligence of a very large group of people using a test designed so that the average score is 100 and the standard deviation is 15 (this is how IQ scores are often measured, but not using a standard normal distribution). To convert these IQ scores into a standard normal distribution, we would adjust the scores so the average comes out to 0 and the spread (standard deviation) is 1. This lets us compare scores in a consistent way, regardless of the original scale.

Let's plot this distribution so you can see what it looks like:


![standard normal distribution](graph.png "Standard normal distribution")

In the graph:

The red dashed line at the center represents the mean of 0.
Annotations indicate the mean (0) and the location of one standard deviation (1) from the mean.
The green bars represent the frequency of different adjusted IQ scores within the distribution.
This graph should give you a clearer idea of how the adjustment of IQ scores to a standard normal distribution would look visually.


In [10]:
np.random.randn(3)

array([ 0.52614659, -0.2772802 ,  0.92351077])

In [11]:
np.random.randn(4,5)

array([[-1.07821824, -0.75509104, -0.10124877, -1.26039079, -0.14156915],
       [ 0.3009643 ,  0.47944161,  1.92264584, -0.08083027, -1.27641372],
       [ 0.72931684,  1.14917836, -0.124508  ,  0.03638239, -0.92889889],
       [-0.80340293, -0.86726571,  0.20726728, -0.28095325, -0.27599026]])

In [13]:
np.random.randint(0,100,5)

array([96, 55, 48, 89, 25])

In [14]:
np.random.randint(0,100,(3,5))

array([[ 9, 67, 46, 84, 58],
       [81, 60, 88, 60, 73],
       [74, 44, 45, 81, 65]])

In [15]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [24]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [27]:
randarr = np.random.randint(0,101,10)
randarr

array([12, 93, 40, 49, 83,  8, 29, 59, 34, 44])

In [29]:
randarr.max()

93

In [30]:
randarr.min()

8

In [31]:
randarr.argmax()

1

In [32]:
randarr.argmin()

5

In [33]:
randarr.dtype

dtype('int64')

In [34]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])