In [1]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[0:5] = 100

In [5]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [6]:
arr = np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:5]

In [10]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [11]:
slice_of_arr[:] = 99

In [12]:
slice_of_arr

array([99, 99, 99, 99, 99])

The broadcast operation on this sliced array will also affect the orignal array.

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 324
arr_copy

array([324, 324, 324, 324, 324, 324, 324, 324, 324, 324, 324])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])