## Conditional Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Following will tell me , which elements of array are > 4

In [4]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
bool_arr = arr > 4

Now it will give elements from array where element is > 4

In [7]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

Above method can be used to filter an array based on some condition. This is very useful when you want to filter out some data from a large dataset.

Here is another shortcut method to acheive same results.

In [9]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [13]:
total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
total_rolls_over_two

19

In [14]:
dice_rolls[dice_rolls > 2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])