# Numpy Operations on 2D Arrays

In [2]:
import numpy as np

In [5]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
arr_2d.shape

(5, 5)

In [8]:
arr_2d.sum()

300

In [9]:
arr_2d.max()

24

Perform sum across rows ||||||

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
       =====================
       50,  55, 60, 65, 70

In [10]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

Perform sum across columns -------

array([[ 0,  1,  2,  3,  4],    = 10
       [ 5,  6,  7,  8,  9],    = 35
       [10, 11, 12, 13, 14],    = 60
       [15, 16, 17, 18, 19],    = 85
       [20, 21, 22, 23, 24]])   = 110


In [11]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [14]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
deposits = account_transactions[account_transactions > 0].sum()
withdrawals = account_transactions[account_transactions < 0].sum()

In [16]:
withdrawals

-830

In [19]:
account_total =  deposits + withdrawals
account_total

2720